name: Check PR Prefix

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check-prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for specific prefix
        uses: actions/github-script@v6
        with:
          script: |
            const prefix = 'Fixes:'; // Define the required prefix here
            const body = context.payload.pull_request.body;
            
            if (!body.startsWith(prefix)) {
              core.setFailed(`PR body must start with "${prefix}".`);
            }
