name: 'PR Tasks Completed Check'
on: 
  pull_request_target:
    types: [opened, edited]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: chromaui/task-completed-checker-action@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
