on:
  issues:
    types: [ labeled, unlabeled ]
#  pull_request:
#    types: [opened, labeled, unlabeled]
#    branches: [master, next, main]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
