name: Sync labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]
    branches: [master, next]
  issues:
    types: [labeled, unlabeled]

jobs:
  label-sync:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Install dependencies
        run: sudo apt-get install -y python3-github

      - name: Pull request opened event
        if: github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/sync_labels.py --repository ${{ github.repository }} --number ${{ github.event.number }} --label_action ${{ github.event.action }}

      - name: Pull request labeled or unlabeled event
        if: github.event_name == 'pull_request' && startsWith(github.event.label.name, 'backport')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/sync_labels.py --repository ${{ github.repository }} --number ${{ github.event.number }} --label_action ${{ github.event.action }} --label ${{ github.event.label.name }}

      - name: Issue labeled or unlabeled event
        if: github.event_name == 'issues' && startsWith(github.event.label.name, 'backport')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/sync_labels.py --repository ${{ github.repository }} --number ${{ github.event.issue.number }} --label_action ${{ github.event.action }} --is_issue --label ${{ github.event.label.name }}
